export default {
    LOAD: 'LOAD',
    BUSCAR_ATIVIDADE: 'BUSCAR_ATIVIDADE',
    SALVAR_ATIVIDADE: 'SALVAR_ATIVIDADE',
    ALTERAR_ATIVIDADE: 'ALTERAR_ATIVIDADE',
    REMOVER_ATIVIDADE: 'REMOVER_ATIVIDADE'
}