export default {
    LOAD: 'LOAD',
    ERROR: 'ERROR',
    BUSCAR_GRUPO_ATIVIDADE: 'BUSCAR_GRUPO_ATIVIDADE',
    SALVAR_GRUPO_ATIVIDADE: 'SALVAR_GRUPO_ATIVIDADE',
    ALTERAR_GRUPO_ATIVIDADE: 'ALTERAR_GRUPO_ATIVIDADE',
    REMOVER_GRUPO_ATIVIDADE: 'REMOVER_GRUPO_ATIVIDADE'
}